# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 03:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(default='', max_length=8)),
                ('address', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('district', models.CharField(max_length=140)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('util_area', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_area', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=140)),
                ('image', models.ImageField(upload_to='img/')),
                ('description', models.TextField()),
                ('rent_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', smart_selects.db_fields.ChainedForeignKey(chained_field='property_type', chained_model_field='property_type', on_delete=django.db.models.deletion.CASCADE, to='properties.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyType'),
        ),
        migrations.AddField(
            model_name='category',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyType'),
        ),
    ]
