# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[(1, 'Apartamentos'), (2, 'Casas')], default=1, max_length=1)),
                ('category', models.CharField(choices=[(1, 'Padrão'), (2, 'Duplex'), (3, 'Triplex'), (4, 'Cobertura'), (5, 'Cobertura Duplex'), (6, 'Cobetura Triplex')], default=1, max_length=1)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('util_area', models.PositiveSmallIntegerField(blank=True)),
                ('total_area', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('rent_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('image', models.ImageField(upload_to='static/img/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
